api_login_check:
    path: /api/login_check

index:
    path: /indexx
    methods: [POST]
    controller: App\Controller\ExamController::index

details:
    path: /api/details
    methods: [GET]
    controller: App\Controller\UserController::details

showUsers:
    path: /api/users
    methods: [GET]
    controller: App\Controller\UserController::showAll

showUser:
    path: /api/user/{id}
    methods: [GET]
    controller: App\Controller\UserController::show

addUser:
    path: /api/user
    methods: [ POST ]
    controller: App\Controller\UserController::add

changePassword:
    path: /api/user/password/{id}
    methods: [POST]
    controller: App\Controller\UserController::changePassword

deleteUser:
    path: /api/user/{id}
    methods: [DELETE]
    controller: App\Controller\UserController::delete

group:
    path: /api/user/{id}/group
    methods: [POST]
    controller: App\Controller\UserController::group

showExam:
    path: /api/exam/{id}
    methods: [GET]
    controller: App\Controller\ExamController::showExam

showExams:
    path: /api/exams
    methods: [GET]
    controller: App\Controller\ExamController::showExams

confirmExam:
    path: /api/exam/confirm/{id}
    methods: [PUT]
    controller: App\Controller\ExamController::confirmExam

startExam:
    path: /api/exam/start/{id}
    methods: [GET]
    controller: App\Controller\ExamController::startExam

userWatchList:
    path: /api/exam/watch-user/{id}
    methods: [GET]
    controller: App\Controller\ExamController::userWatchList

watchExam:
    path: /api/exam/watch/{examId}/user/{userId}
    methods: [GET]
    controller: App\Controller\ExamController::watchExam

joinExam:
    path: /api/exam/join/{id}
    methods: [GET]
    controller: App\Controller\ExamController::joinExam

updateResult:
    path: /api/exam/result/{id}
    methods: [POST]
    controller: App\Controller\ExamController::updateResult

getResults:
    path: /api/results
    methods: [GET]
    controller: App\Controller\ExamController::getResults

closeResult:
    path: /api/exam/close/{id}
    methods: [GET]
    controller: App\Controller\ExamController::closeResult

addExam:
    path: /api/exam
    methods: [POST]
    controller: App\Controller\ExamController::addExam

showTests:
    path: /api/tests
    methods: [GET]
    controller: App\Controller\TestController::showTests

showTest:
    path: /api/test/{id}
    methods: [GET]
    controller: App\Controller\TestController::showTest

addTest:
    path: /api/test
    methods: [POST]
    controller: App\Controller\TestController::addTest

showQuestions:
    path: /api/questions
    methods: [GET]
    controller: App\Controller\TestController::showQuestions

showQuestion:
    path: /api/question/{id}
    methods: [GET]
    controller: App\Controller\TestController::showQuestion

addQuestion:
    path: /api/question
    methods: [POST]
    controller: App\Controller\TestController::addQuestion

archiveExam:
    path: /api/exam/archive/{id}
    methods: [GET]
    controller: App\Controller\ExamController::archiveExam
