api_login_check:
    path: /api/login_check

showUsers:
    path: /api/users
    methods: [GET]
    controller: App\Controller\UserController::showAll

showUser:
    path: /user/{id}
    methods: [GET]
    controller: App\Controller\UserController::show

addUser:
    path: /user
    methods: [ POST ]
    controller: App\Controller\UserController::add

changePassword:
    path: /user/password/{id}
    methods: [POST]
    controller: App\Controller\UserController::changePassword

deleteUser:
    path: /user/{id}
    methods: [DELETE]
    controller: App\Controller\UserController::delete

group:
    path: /user/{id}/group
    methods: [POST]
    controller: App\Controller\UserController::group

showExam:
    path: /exam/{id}
    methods: [GET]
    controller: App\Controller\ExamController::showExam

showExams:
    path: /exams
    methods: [GET]
    controller: App\Controller\ExamController::showExams

confirmExam:
    path: /exam/confirm/{id}
    methods: [PUT]
    controller: App\Controller\ExamController::confirmExam

startExam:
    path: /exam/start/{id}
    methods: [PUT]
    controller: App\Controller\ExamController::startExam

addExam:
    path: /exam
    methods: [POST]
    controller: App\Controller\ExamController::addExam

showTests:
    path: /tests
    methods: [GET]
    controller: App\Controller\TestController::showTests

showTest:
    path: /test/{id}
    methods: [GET]
    controller: App\Controller\TestController::showTest

addTest:
    path: /test
    methods: [POST]
    controller: App\Controller\TestController::addTest

showQuestions:
    path: /questions
    methods: [GET]
    controller: App\Controller\TestController::showQuestions

showQuestion:
    path: /question/{id}
    methods: [GET]
    controller: App\Controller\TestController::showQuestion

addQuestion:
    path: /question
    methods: [POST]
    controller: App\Controller\TestController::addQuestion